### ISSUE TITLE
Modules and general problem

### ISSUE THREAD

**Issue by Ste-denko** [maplibre/ngx-maplibre-gl#12]
Hi All,
I followed the exact documentation from Readme file and ended up with these error messages:

```
Error: node_modules/maplibre-gl/src/index.d.ts:16:23 - error TS2688: Cannot find type definition file for 'geojson'.

16 /// <reference types="geojson" />

Error: node_modules/maplibre-gl/src/index.d.ts:1237:23 - error TS2503: Cannot find namespace 'GeoJSON'.

1237         setData(data: GeoJSON.Feature<GeoJSON.Geometry> | GeoJSON.FeatureCollection<GeoJSON.Geometry> | String): this
```

(and many more like this, always pointing to GeoJSON)

When installing @types/mapbox-gl these errors are not shown anymore but is this the right way to do it,
or might this be causing other troubles?
I am asking this because once I am done with all steps from the Readme file (also installing @types/mapbox-gl) I would expect to see a map, but nothing is showing up.
The mgl-map component seems to be correctly created with height: 100% and width: 100%.
I am testing this in a newly created Angular project.

Any hint or suggestions would be really appreciated.
Thanks in advance.
Cheers

**Comment by HarelM** [comment]
You need to install types/geojson, I think.
This will be solved in next release, but until then I believe this is the right solution.

**Comment by HarelM** [comment]
You can check the code in the demo (documentation) pages to see working examples in stack blitz that uses angular.

**Comment by HarelM** [comment]
Feel free to send any PR to update the documentation :-)

**Comment by Ste-denko** [comment]
> You need to install types/geojson, I think.
> This will be solved in next release, but until then I believe this is the right solution.

Thanks, and yes, that solved the error message.

> You can check the code in the demo (documentation) pages to see working examples in stack blitz that uses angular.

Would you be so kind and provide a link to the demo (documentation) you are talking about? I simply cannot find anything helpful.
(If you mean the documentation from the Readme file ... as I mentioned above, that did not work for me ;o)

Thank you VERY MUCH, also for the super fast replies.
Cheers

**Comment by HarelM** [comment]
No problem, can I close this issue or do you think something should be added somewhere?
The documentation is here:
https://maplibre.org/ngx-maplibre-gl/
I'll update the readme to link there.

**Comment by HarelM** [comment]
I've updated the readme, and partially the API.md.
If you have a few minutes to spare to send a PR for updating the API.md links to point to maplibre documentation instead of mapbox documentation it would be extremely helpful :-)

**Comment by Ste-denko** [comment]
> No problem, can I close this issue or do you think something should be added somewhere?
> The documentation is here:
> https://maplibre.org/ngx-maplibre-gl/
> I'll update the readme to link there.

Thanks again for all your help and efforts.
I would like to mention that my problem is fixed meanwhile, but unfortunately it still exists, although I followed all the provided documentation.

This is what I did:

- Created a fresh, blank and default Angular project
- Executed: npm install ngx-maplibre-gl maplibre-gl @types/geojson
- Modified the project files as shown in the documentation and demo.

The related files are then looking like this:

angular.json
```
...
"styles": [
  "src/styles.css",
  "./node_modules/maplibre-gl/dist/maplibre-gl.css"
],
...
```



polyfills.ts
```
...
(window as any).global = window;
...
```



app.module.ts
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { NgxMapLibreGLModule } from 'ngx-maplibre-gl';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgxMapLibreGLModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```


app.component.ts
```
import { Component } from '@angular/core';

@Component({
  template: `
    <mgl-map
      [style]="'https://api.maptiler.com/maps/streets/style.json?key=MyOwnValidKey'"
      [zoom]="[9]"
      [center]="[-74.50, 40]"
    >
    </mgl-map>
  `,
  styles: [
    `
      mgl-map {
        height: 100%;
        width: 100%;
      }
    `,
  ],
})
export class AppComponent {}

```

The code succesfully compiles but the preview window still remains just white without a map.
What am I missing here?
Any help would be really appreciated.
Thanks again in advance.

**Comment by HarelM** [comment]
You need a style and tiles source I guess...?
Please share the relevant code and I might be able to help...

**Comment by Ste-denko** [comment]
The style source is given here in the app.component.ts:

`[style]="'https://api.maptiler.com/maps/streets/style.json?key=MyOwnValidKey'"`

Where to provide the vector tiles source? Cannot find this in the docu.

**Comment by HarelM** [comment]
This is less related to this project.
This project only wraps maplibre. You should consult their documentation for style and tile sources. Note that version 2 is still in pre release and should not be used.
You can use the demotiles repo or get a key from maptiler.

**Comment by HarelM** [comment]
Closing...
